version: '3.7'

services:
  jingjing:
    container_name: jingjing
    image: jingjing
    environment:
      - DATABASE=db
      - USERNAME=user
      - PASSWORD=password
      - HOST=locashot
      - PORT=3306
    networks:
      - proxy

networks:
  proxy:
    external: true
